-- TABLE STRUCTURE PCA1 GROUP C
-- STUDENT(ST_ROLL, ST_NAME, ST_ADDR)
-- TEACHER(T_NAME, T_ADDR, T_DESIG)
-- SUBJECT(SUB_ID, T_NAME)
-- CLASS(CL_R_NO, YEAR, SUB_ID)
-- MARKS(SUB_ID, ST_ROLL, MARKS)

-- Q1: FIND THE TOTAL MARKS OBTAIN BY A STUDENT

-- Q2: LIST THE NAMES OF STUDENT WHO GOT MAX MARKS SUBJECT WISE

-- Q3: FIND THE NAME OF THE STUDENT WHO GOT MAX TOTAL MARKS. 
