SELECT * FROM WORKER;

-- BETWEEN
SELECT FIRST_NAME, SALARY
FROM WORKER 
WHERE SALARY BETWEEN 100000 AND 500000;

-- IN [REDUCE OF MULTIPLE OR OPERATOR]
SELECT FIRST_NAME, LAST_NAME
FROM WORKER
WHERE FIRST_NAME IN ('Monika','Vivek');

-- WILDCARD & USE OF LIKE
SELECT * 
FROM WORKER
WHERE FIRST_NAME LIKE '%ik%';

-- DISTINCT
-- QUERY: HOW MANY DEPARTMENT ARE AVAINABLE IN WORKER TABLE
SELECT DISTINCT DEPARTMENT
FROM WORKER;
