-- JOINING IN RDBMS [THEORY]

-- INNER JOIN
SELECT C.*, O.* 
FROM CUSTOMER AS C INNER JOIN ORDERS AS O
ON C.ID = O.CUST_ID;

-- LEFT JOIN
SELECT C.*, O.*
FROM CUSTOMER AS C LEFT JOIN ORDERS AS O
ON C.ID = O.CUST_ID;

-- RIGHT JOIN
SELECT C.*, O.*
FROM CUSTOMER AS C RIGHT JOIN ORDERS AS O
ON C.ID = O.CUST_ID;

-- FULL JOIN
SELECT * 
FROM LEFT_TABLE AS L LEFT JOIN RIGHT_TABLE AS R 
ON L.KEY = R.KEY
UNION
SELECT *
FROM LEFT_TABLE AS L RIGHT JOIN RIGHT_TABLE AS R
ON L.KEY = R.KEY;

-- CROSS JOIN [CARTISION PRODUCT]
-- NO INDUSTRIAL USE

-- SELF JOIN
SELECT E1.ID, E2.ID, E2.NAME
FROM EMPLOYEE AS E1 INNER JOIN EMPLOYEE AS E2
ON E1.ID = E2.ID;