-- USE OF ALTER
CREATE TABLE ACCOUNT(
	id INT PRIMARY KEY,
	name VARCHAR(120),
	balance INT NOT NULL DEFAULT 0 
); 

INSERT INTO ACCOUNT 
	(id, name, balance) VALUES
    (1, 'sumit', 12000),
    (2, 'snehasis', 52000),
    (3, 'dipali', 32000),
    (4, 'rounak', 5000);
    
SELECT * FROM ACCOUNT;

-- QUERY: ADD A NEW INTEREST COLUMN
ALTER TABLE ACCOUNT
ADD interest FLOAT NOT NULL DEFAULT 0;

DESC ACCOUNT;

-- QUERY: CHANGE THE DATATYPE
ALTER TABLE ACCOUNT
MODIFY interest DOUBLE NOT NULL DEFAULT 0;

-- QUERY: RENAME THE COLUMN
ALTER TABLE ACCOUNT
CHANGE COLUMN interest saving_interest FLOAT NOT NULL DEFAULT 0;

-- QUERY: DROP THE COLUMN
ALTER TABLE ACCOUNT
DROP COLUMN saving_interest;

-- QUERY: RENAME THE TABLE
ALTER TABLE ACCOUNT
RENAME TO ACCOUNT_DETAILS;