-- QUERY: FIND NO OF EMPLOYEES WORKING IN DIFFERENT DEPARTMENT
-- AGGRIGATION(COUNT)
SELECT DEPARTMENT
FROM WORKER
GROUP BY DEPARTMENT;
-- GROUP BY WITHOUT USING AGGIRGATION FUNCTION IS MEANS DISTINCT

SELECT DEPARTMENT, COUNT(*) NO_OF_EMPLOYEES
FROM WORKER
GROUP BY DEPARTMENT;

-- WHEN WE NEED DEPARTMENT WISE, COUNTRY WISE COUNT DATA THEN WE USE GROUP BY

-- QUERY: FIND THE AVERAGE SALARY DEPARTMENT WISE
SELECT DEPARTMENT, AVG(SALARY)
FROM WORKER 
GROUP BY DEPARTMENT; 

-- QUERY: FIND DEPARTMENT WISE MIN SALARY
SELECT DEPARTMENT, MIN(SALARY) MIN_SALARY
FROM WORKER
GROUP BY DEPARTMENT;

-- QUERY: FIND THE COUNT OF THE DEPARTMENT WHERE HAVING MORE THAN 2 WORKERS
SELECT DEPARTMENT, COUNT(DEPARTMENT)
FROM WORKER
GROUP BY DEPARTMENT
HAVING COUNT(DEPARTMENT)>2;

SELECT * FROM WORKER;